IF OBJECT_ID ('cdm_schema.care_site', 'U') IS NOT NULL
  DROP TABLE cdm_schema.care_site;

CREATE TABLE cdm_schema.care_site (
  care_site_id INT NOT NULL, -- Autogenerated
  care_site_name NVARCHAR(255),
  place_of_service_concept_id INT DEFAULT 0,
  location_id INT, -- CAST(null as integer)?
  care_site_source_value NVARCHAR(50),
  place_of_service_source_value NVARCHAR(50)
);

INSERT INTO cdm_schema.care_site (
  care_site_id,
  care_site_name,
  place_of_service_concept_id,
  location_id,
  care_site_source_value,
  place_of_service_source_value
)
SELECT
  ROW_NUMBER() OVER (O.id),   -- care_site_id
  O.name,                     -- care_site_name
  0,                          -- place_of_service_concept_id
  CAST(NULL AS INT),          -- location_id
  O.id,                       -- care_site_source_value
  CAST(NULL AS NVARCHAR)      -- place_of_service_source_value
FROM synthea_schema.organizations AS O
;
