IF OBJECT_ID ('cdm_schema.care_site', 'U') IS NOT NULL
  DROP TABLE cdm_schema.care_site;

CREATE TABLE cdm_schema.care_site (
  care_site_id INT, -- Autogenerated
  care_site_name NVARCHAR(255),
  place_of_service_concept_id INT DEFAULT 0,
  location_id INT, -- CAST(null as integer)?
  care_site_source_value NVARCHAR(50),
  place_of_service_source_value NVARCHAR(50)
);
