IF OBJECT_ID ('cdm_schema.observation_period', 'U') IS NOT NULL
  DROP TABLE cdm_schema.observation_period;

CREATE TABLE cdm_schema.observation_period (
  observation_period_id INT IDENTITY(1, 1) NOT NULL, -- Autogenerated
  person_id INT NOT NULL,
  observation_period_start_date DATE,
  observation_period_end_date DATE,
  period_type_concept_id INT
);
