IF OBJECT_ID ('cdm_schema.person', 'U') IS NOT NULL
  DROP TABLE cdm_schema.person;

-- I'll create all the columns for the ETL-Synthea builder for now
CREATE TABLE cdm_schema.person (
  person_id INT NOT NULL, -- This should be autogenerated; The insert file they have uses ROW_NUMBER() instead of IDENTITY()
  gender_concept_id INT, -- Rows with missing/unknown gender should be dropped
  year_of_birth INT,
  month_of_birth INT,
  day_of_birth INT,
  birth_datetime DATETIME,
  death_datetime DATETIME,
  race_concept_id INT,
  ethnicity_concept_id INT,
  location_id INT,
  provider_id INT,
  care_site_id INT,
  person_source_value NVARCHAR(50),
  gender_source_value NVARCHAR(50),
  gender_source_concept_id INT,
  race_source_value NVARCHAR(50),
  race_source_concept_id INT,
  ethnicity_source_value NVARCHAR(50),
  ethnicity_source_concept_id INT
);

INSERT INTO cdm_schema.person (
  person_id, 
  gender_concept_id,
  year_of_birth,
  month_of_birth,
  day_of_birth,
  birth_datetime,
  -- death_datetime,
  race_concept_id,
  ethnicity_concept_id,
  location_id,
  provider_id,
  care_site_id,
  person_source_value,
  gender_source_value,
  gender_source_concept_id ,
  race_source_value,
  race_source_concept_id,
  ethnicity_source_value,
  ethnicity_source_concept_id
)
SELECT
  ROW_NUMBER() OVER (ORDERY BY P.id), -- person_id
  CASE UPPER(P.gender)
    WHEN 'M' THEN 8507
    WHEN 'F' THEN 8532
  END, -- gender_concept_id
  YEAR(P.birthdate), -- Year
  MONTH(P.birthdate), -- Month
  DAY(P.birthdate), -- Day
  CASE UPPER(P.race)
    WHEN 'WHITE' THEN 8527
    WHEN 'BLACK' THEN 8516
    WHEN 'ASIAN' THEN 8515
    ELSE 0
  END, -- race_concept_id
  CASE UPPER(P.race)
    WHEN 'HISPANIC' THEN 38003563
    ELSE 0
  END, -- ethnicity_concept_id
  NULL, -- location_id
  NULL, -- provider_id
  NULL, -- care_site_id
  P.id, -- person_source_value
  P.gender, -- gender_source_value
  0, -- gender_source_concept_id
  P.race, -- ethnicity_source_value
  0 -- ethnicity_source_concept_id
FROM synthea_schema.patients AS P
WHERE P.gender IS NOT NULL
;
