/*
===============================================================================
Magnitude Analysis
===============================================================================
*/
-- Total customers by shipping state (q_id = 8)

WITH user_states AS (
	SELECT
		  response_id
		, answer_id
	FROM silver.user_answers
	WHERE q_id = 8
)
SELECT
	  answers.answer_text
	, COUNT(DISTINCT response_id) AS residents
FROM user_states
INNER JOIN silver.answers
	ON user_states.answer_id = answers.answer_id
GROUP BY answer_text
;

-- Total Order Shipped to each State
SELECT
	  shipping_address_state
	, COUNT(*)
FROM silver.amazon_purchases
GROUP BY shipping_address_state
;

-- Total customers by gender

-- Total products by category

-- Average price in each category

-- Total revenue generated for each category

-- Total revenue generated by each customer

-- Total categories bought from by each customer
SELECT
	  response_id
	, COUNT(DISTINCT category) AS num_categories_bought
	, SUM(quantity * purchase_price_per_unit) AS revenue_generated
FROM silver.amazon_purchases
GROUP BY response_id
;

-- Distribution of customers across states
